[project]
name = "portfolio-optimization"
version = "0.1.0"
dependencies = [
    "arch>=8.0.0",
    "ipykernel>=6.31.0",
    "notebook>=7.4.7",
    "numba>=0.62.1",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "yfinance>=0.2.66",
]
